# Generated by Django 5.0.7 on 2024-07-28 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('product_description', models.TextField()),
                ('product_release_date', models.DateField(auto_now_add=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_width', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_category', to='category.category')),
            ],
        ),
    ]
