# Generated by Django 5.0.7 on 2024-08-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_product_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='delete',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
