# Generated by Django 5.0.7 on 2024-08-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productimage_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='delete',
        ),
    ]
